git:
  depth: 10

branches:
  only:
    - master

env:
  global:
    - ATOM_ACCESS_TOKEN=da809a6077bb1b0aa7c5623f7b2d5f1fec2faae4

compiler: clang

matrix:
  include:
    - os: linux
      env: NODE_VERSION=4.2.1
    - os: linux
      env: NODE_VERSION=0.10.35
    - os: osx
      env: NODE_VERSION=4.2.1
    - os: osx
      env: NODE_VERSION=0.10.35

sudo: false

install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - npm config delete prefix
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
  - yes | cp apm/package-node-$NODE_VERSION.json apm/package.json
  - yes | cp build/package-node-$NODE_VERSION.json build/package.json

script: script/cibuild

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
