git:
  depth: 10

branches:
  only:
    - master

env:
  global:
    - ATOM_ACCESS_TOKEN=da809a6077bb1b0aa7c5623f7b2d5f1fec2faae4

compiler: clang

language: node_js

node_js:
  - "4.2.1" # apm 1.5.x
  - "0.10.35" # apm 1.4.x

matrix:
  include:
    - os: linux
    - os: osx

sudo: false

install:
  - yes | cp apm/package-node-$TRAVIS_NODE_VERSION.json apm/package.json
  - yes | cp build/package-node-$TRAVIS_NODE_VERSION.json build/package.json
  - if [ $TRAVIS_OS_NAME == "osx" ]; then brew install moreutils; fi

script: script/cibuild | ts

cache:
  directories:
    - $HOME/.atom/.apm
    - $HOME/.atom/.npm

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - moreutils
