version: "{build}"

branches:
  only:
    - jf-add-appveyor-build

skip_tags: true
clone_folder: c:\projects\atom
clone_depth: 10

platform:
  - x86
  - x64

environment:
  ATOM_DEV_RESOURCE_PATH: c:\projects\atom
  ATOM_ACCESS_TOKEN:
    secure: Q7vxmSq0bVCLTTRPzXw5ZhPTe7XYhWxX0tQV6neEkddTH6pZkOYNmSCG6VnMX2f+

install:
  - SET PATH=C:\Program Files\Atom\resources\cli;%PATH%
  - ps: Install-Product node 4.2.1 $env:PLATFORM

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\projects\atom\script\cibuild.cmd
  - SET PATH=C:\Program Files\Atom\resources\cli;%PATH%

test: off
deploy: off
