version: "{build}"

branches:
  only:
    - jf-add-appveyor-build

skip_tags: true
clone_folder: c:\projects\atom
clone_depth: 10

platform:
  - x86
  - x64

environment:
  global:
    ATOM_DEV_RESOURCE_PATH: c:\projects\atom
    ATOM_ACCESS_TOKEN:
      secure: Q7vxmSq0bVCLTTRPzXw5ZhPTe7XYhWxX0tQV6neEkddTH6pZkOYNmSCG6VnMX2f+

  matrix:
  - NODE_VERSION: 4.2.1
  - NODE_VERSION: 0.10.35

matrix:
  allow_failures:
    - NODE_VERSION: 0.10.35

install:
  - SET PATH=C:\Program Files\Atom\resources\cli;%PATH%
  - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM

before_build:
  - copy /y %APPVEYOR_BUILD_FOLDER%\apm\package-node-%NODE_VERSION%.json %APPVEYOR_BUILD_FOLDER%\apm\package.json
  - copy /y %APPVEYOR_BUILD_FOLDER%\build\package-node-%NODE_VERSION%.json %APPVEYOR_BUILD_FOLDER%\build\package.json

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\projects\atom\script\cibuild.cmd

test: off
deploy: off
artifacts:
  - path: atom-build

cache:
  - '%USERPROFILE%\.atom\.apm'
  - '%USERPROFILE%\.atom\.npm'
